### ISSUE TITLE
Crop tool should only crop inside the content, not outside of the content

### ISSUE THREAD

**Issue by probonopd** [stippi/WonderBrush-v2#15]
The Crop tool should only crop inside the content, not outside of the content.

Currently it is very hard to e.g., cut out the upper right-hand corner of a picture because you will always capture some of the empty checkerboard space.

**Comment by stippi** [comment]
Rejecting, as this is on purpose. You can use the Crop tool also to **extend** the drawing area. Your use-case is still covered: Press the `All` button of the Crop tool's UI, then drag the bottom and left side of the crop area.

That being said, it would be nice if the Crop tool *snapped* to the image borders by default.

**Comment by probonopd** [comment]
Thanks for the clarification @stippi 

> it would be nice if the Crop tool snapped to the image borders by default.

:+1:
