### ISSUE TITLE
Build failure with gcc2

### ISSUE THREAD

**Issue by humdingerb** [stippi/WonderBrush-v2#17]
Build fails with:

```
/Source/WonderBrush-v2/common/src/gui/BubbleHelper.cpp: In method `BubbleHelper::BubbleHelper()':
/Source/WonderBrush-v2/common/src/gui/BubbleHelper.cpp:67: passing `int (*)(void *)' as argument 1 of `spawn_thread(status_t (*)(void *), const char *, long int, void *)'
/Source/WonderBrush-v2/common/src/gui/BubbleHelper.cpp: At top level:
/Source/WonderBrush-v2/common/src/gui/BubbleHelper.cpp:297: new declaration `static status_t BubbleHelper::_helper(void *)'
/Source/WonderBrush-v2/common/src/gui/BubbleHelper.h:60: ambiguates old declaration `static int BubbleHelper::_helper(void *)'
```

Looks like the return of _helper() in common/src/gui/BubbleHelper.h should be "status_t" as it was changed from "int" with c2173f698a6365c4190843f6944b2a5dd54caf87.

Build still fails with that change though:
`/packages/gcc-2.95.3_2017_07_20-2/.self/develop/tools/i586-pc-haiku/bin/ld: cannot find -lstdc++
`

PulkoMandy suggested to switch from 'gcc' to 'g++' to pick the right library when using gcc2/8. But I caan't find where to do that...

**Comment by diversys** [comment]
I think this can be closed now.

**Comment by pulkomandy** [comment]
Yes, the pull request has been merged and fixes this.
