### ISSUE TITLE
crash on launch hrev54460

### ISSUE THREAD

**Issue by bbjimmy** [stippi/WonderBrush-v2#19]
crash report: http://fatelk.com/jim/WonderBrush-555-debug-25-07-2020-15-52-37.report.zip

**Comment by waddlesplash** [comment]
Fixed in https://git.haiku-os.org/haiku/commit/?id=d548fb2b3e493004761739c3e3fcc008ec497860

**Comment by bbjimmy** [comment]
Indeed it now woeks.

**Comment by diversys** [comment]
This issue can be closed.
