### ISSUE TITLE
Wonderbrush 64bit crash when clicking settings tab by first start

### ISSUE THREAD

**Issue by Brunobasta** [stippi/WonderBrush-v2#20]
Installed Wonderbrush with HaikuDepot opened it and tried to change settings... it crashed
after reboot next day no more crash!?

**Comment by diversys** [comment]
Maybe it crashed while creating a settings file and once it's there it doesn't crash anymore?

**Comment by Brunobasta** [comment]
Now it crashes when trying to open the language Tab again, nothing I changed. How and where to upload the crash report?

**Comment by pulkomandy** [comment]
Please try Haiku hrev54798 or later.

**Comment by Brunobasta** [comment]
works now will have to deinstall and clear the settings file and install again to investigate further...
now on hrev54798 64bit

**Comment by Brunobasta** [comment]
ok all bugs solved, found no more atm...
Great work, very very happy I am, thx
