### ISSUE TITLE
Wonderbrush 64 crashes on Save as window

### ISSUE THREAD

**Issue by Briseur** [stippi/WonderBrush-v2#21]
Opened Wonderbrush, checked settings, opened new canvas, draw a simple form, selected Save as..
Nothing happened at window opening but when I tried to select a different format Wonderbrush crashed.

**Comment by Briseur** [comment]
Tried to upload report, with Web+ and Otter, it doesn't seem to work at all.
Tried with FF on linux... "We don't support that file type." 
So I zipped it.

[report.zip](https://github.com/stippi/WonderBrush-v2/files/5710658/report.zip)

**Comment by stippi2** [comment]
@waddlesplash can you have a look? You've done the 64-bit port and I don't even have a 64-bit install of Haiku at hand.

**Comment by Briseur** [comment]
Forgot to mention it's on nightly hrev54795

**Comment by waddlesplash** [comment]
Maybe it is somehow related to the recent fix @kallisti5 did to IOM? https://git.haiku-os.org/haiku/commit/?id=69b1d7ac94338545fc7e1d27afaf37b6836d8108

**Comment by pulkomandy** [comment]
Please try Haiku hrev54798 or later.

**Comment by Briseur** [comment]
Save as file types dropdown menu is a bit puzzling, it should show Wonderbrush format even if everything else is greyed out.
At least, it doesn't crash with hrev54798 so this one seems resolved.

**Comment by kallisti5** [comment]
I was thinking about this... by modifying the layout of the save dialogs, are we breaking BeOS compat?

I mean, the layout kit is better for sure, but it seems like a lot of older apps "adjust" the save dialog and don't have code paths for properly adjusting the save dialog when things can't be found (icon-o-matic for example)

Hopefully though @pulkomandy is right on the real fix :-)

**Comment by kallisti5** [comment]
Oh.. he was right :-)  missed @Briseur 's response.

Either way, I can't think of many BeOS ABI-only apps that are still useful. So meh.

**Comment by pulkomandy** [comment]
A bit off-topic to discuss here, but, yes. Waddlesplash did the layoutification of BFilePanel and there were complaints about that. The most obvious issues had been fixed back then. But we're at risk of breaking things again everytime we touch BPoseView or do any other change to the filepanel.
